### ISSUE TITLE
Display the blocked requests in the add-on icon.

### ISSUE THREAD

**Issue by MrJustMe** [keraf/NoCoin#101]
What do you think about showing the number of requests blocked by the add-on icon instead of the exclamation point currently displayed?.
I realize that of the 7 add-on I have installed, they all show a numerical indicator instead of a symbol, except for 2 and No Coin is one of them. If you don't know what I'm talking about, install ublock origin and look at the number on its icon, that's what I mean. This is not a bug, it's a cosmetic change. I put it over here because you're asking for feature requests to be posted here and nice work!, thanks!.

**Comment by keraf** [comment]
This has been suggested previously but wasn't added because it doesn't make much sense. I don't think any website would run more than one miner on a page and there's therefore no need to indicate how many requests were blocked. Instead just indicating that a miner has been blocked is enough. This is different to adblockers or some privacy extensions because websites usually have multiple ads or trackers on a page. 

I will in the future add stats so you'll be able to see how many requests were blocked per day.

I'll leave this issue open for discussion a few more days.

**Comment by MrJustMe** [comment]
I think they're good reasons for not doing it, as I say it's just a cosmetic change, although it can be useful in some cases, for example, I just installed another blocker that has this function included, if yours also had it, I could make a visual check about which one is better or more suited to my needs, or if any of them are leaving something to block in the way because I really think that a website can have more than one miner on a page.
If you own the site and someone is blocking you from using one of the miners, you can use another for example.
I include two "temporary" screenshots from my browser:
[Case 1](https://i.imgur.com/FNk2NCD.png)  shows two blocks, so I assume the page tries to run two miners. I haven't really checked.
[Case 2](https://i.imgur.com/cF0l5SG.png) shows a good number of blockages, as these blockages increase in time, I assume that there is at least one miner trying to run itself every X time and the add-on is reporting those attempts to me.
Anyway, your code, your decision, you'll always do the right thing.
