### ISSUE TITLE
Coin miner block list

### ISSUE THREAD

**Issue by MertcanGokgoz** [keraf/NoCoin#107]
Hi

I thought you could use the following list, I think all domains are there

https://raw.githubusercontent.com/ZeroDot1/CoinBlockerLists/master/hosts

**Comment by keraf** [comment]
Hi, 

Thanks for the list. Unfortunately it is not a format that No Coin supports. Additionally, No Coin is more specifically targeting the ressources containing the miners instead of blocking whole domains. This allows users to still access a ressource they wish to see but without any miners active.

If you have any ressources you would want No Coin to block, feel free to submit a PR or open an issue with an example of the site using a miner. 

Cheers!
