### ISSUE TITLE
Block not work on https://www.onlinevideoconverter.com/video-converter

### ISSUE THREAD

**Issue by ssavva05** [keraf/NoCoin#127]
please update it because more and more sites use coin miners !
  You get the script after you download a video

**Comment by Firminator** [comment]
Didn't see any mining. Anyone else?

**Comment by ssavva05** [comment]
I have also ad blocker installed.
I find a youtube video , then add it here to download it . 
At the end i Get this script as present! 
![image](https://user-images.githubusercontent.com/22216008/34733662-d4d7880c-f571-11e7-90b1-861d12a1dd13.png)

**Comment by ssavva05** [comment]
try it

**Comment by Firminator** [comment]
You're right. https://zxc1-ustokyyneikyfasnm.stackpathdns.com/assets/javascript/cr.js is an obfuscated mining script. Is that SCEP/WindowsDefender/SecurityEssentials who detected the file?

The French EasyList allows loading anything from stackpathdns.com/assets/, so that's something that first need to be adressed. Else we can start adding the block.

**Comment by ssavva05** [comment]
The eset antivirus is that who detect the script. It will be nice if you can start add it in the block. Thanks in Advance!

**Comment by ssavva05** [comment]
I will close this issues , but please update the block list!
