### ISSUE TITLE
Please support Safari.

### ISSUE THREAD

**Issue by Chamiu** [keraf/NoCoin#13]

**Comment by keraf** [comment]
I have not looked into supporting Safari yet as I don't have a Mac but I read some docs and find a guinea pig. This is not high on my priority list though, I'm looking to first improve the extension before focusing on porting it over to other browsers.

**Comment by keraf** [comment]
I've done some reading and I saw that the developer fee for publishing extensions for Safari is 100$ a year. Can someone confirm this is true? If yes, I guess the Safari port might not happen.

**Comment by keraf** [comment]
I just read the documentation on Apple's website. I am sorry but the Safari port won't happen simply because I don't own a Mac and I won't be able to properly maintain it. 

If someone is up for forking No Coin, porting it for Safari, maintain it and take care of pushing the updates to the Safari Addon Gallery, be my guest.

**Comment by miki2o** [comment]
I can make all the possible to help you with a mac. You can install safari extensions also without publishing them to the "store"
