### ISSUE TITLE
Please add "Block all", not only on white list for X min.

### ISSUE THREAD

**Issue by athagoras** [keraf/NoCoin#35]
I don't like to give any resources for any website to mine the coin.
But in 0.4.0 don't have block all bitcoin option.
Please add this option, but I don't need you to set it by default for some reason.

**Comment by keraf** [comment]
I'm not sure I understand. By default all coin miners from the blacklist are blocked and the white list feature allows you to allow temporarily or permanently a domain to bypass that blacklist.

**Comment by athagoras** [comment]
I don't know you added some website into whitelist by default?

**Comment by keraf** [comment]
cnhv.co was added to the whitelist by defaults because it is not abusing your computer for mining. It is the shortlink service run by Coin Hive and is mining for a very short amount of time. The reason why it was added there as well was not to block users that would download No Coin for Firefox on Android as there is currently no wait to white list a domain as the pop up does not work.

If you wish to block cnhv.co, you can do so by removing it from the white list when you are visiting the domain. It will be removed from the defaults once there is a solution for Firefox Android to white list domains.
