### ISSUE TITLE
We want Nocoin to firefox!

### ISSUE THREAD

**Issue by Vinicius379** [keraf/NoCoin#91]
please help us to use this extension too

**Comment by gadcam** [comment]
Did you try to download it from there ? https://addons.mozilla.org/en-US/firefox/addon/no-coin/

**Comment by Firminator** [comment]
Exactly. Issue can be closed.

**Comment by rdzogschen** [comment]
Page not found…

**Comment by andyklimczak** [comment]
Page is broken

**Comment by Maverynthia** [comment]
Not even searching it gives results.

**Comment by Firminator** [comment]
Nov 2nd it was there[1]. Nov 11th it was there. 13hrs later it wasn't. Keraf might have taken it down. I have no idea.

[1] https://web.archive.org/web/20171102075833/https://addons.mozilla.org/en-US/firefox/addon/no-coin/

**Comment by keraf** [comment]
I did not remove it, it simply didn't pass the submission process because of the way I attach the source of the extension. I always linked to the tag on Github of the version I was uploading but they require you to upload the zipped source with instructions on their site (I never noticed that upload form...). I will re-upload the package later today and hopefully it will pass submission quickly enough to be back today or tomorrow. 

I'll close this issue in favour of #98.
